Readme and Install files changed
lbryio/odysee-roku pull request #8
Opened 2021-04-05 10:55 UTC by iamflorencejay

It is obvious

2021-04-26 08:15 UTC, iamflorencejay commented
@s9260 im done what you've ask. 😆

2021-05-26 22:21 UTC, s9260 requested changes
Change L45 (readme) to:
```This project is licensed under the GNU General Public License Version 3.0. For the full license, see [LICENSE](LICENSE).```
Other than that, perfect except for screenshots.
Build off of bf826716fe3813b895f289b452862e80c9c17a34 (indev) to get closest to current production, I'm changing Views -> LBC so I stop abusing the views API endpoint so much.

2021-05-30 16:51 UTC, iamflorencejay commented
@s9260 done

2021-06-12 00:43 UTC, s9260 commented on README.md
> +We take security seriously. Please contact security@lbry.com regarding any security issues. Our PGP key is [here](https://keybase.io/lbry/key.asc) if you need it. All releases are signed by [Sean Yes
```suggestion
We take security seriously. Please contact security@lbry.com regarding any security issues. Our PGP key is [here](https://keybase.io/lbry/key.asc) if you need it.
```

2021-06-12 00:45 UTC, s9260 commented on README.md
> +We take security seriously. Please contact security@lbry.com regarding any security issues. Our PGP key is [here](https://keybase.io/lbry/key.asc) if you need it. All releases are signed by [Sean Yes
```suggestion
We take security seriously. Please contact security@lbry.com regarding any security issues. Our PGP key is [here](https://keybase.io/lbry/key.asc) if you need it.
```

2021-06-12 00:45 UTC, s9260 commented on INSTALL.md
> +If you want to debug, clone this repository and go to roku-main-channel folder. You can see the core files such as components, images, etc.
```suggestion
If you want to debug, clone this repository and go to the MVP-Roku folder. You can see the core files such as components, images, etc.
```

2021-06-12 01:00 UTC, merged